[package]
name = "web3_rust_wrapper"
version = "0.2.0"
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
web3 = "0.17.0"
tokio = { version= "1", features = ["full"] }
dotenv = "0.15.0"
secp256k1 = "0.20.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.19"
open = "2.0.2"
colored = "2.0.0"
sysinfo = "0.23.0"
rand = "0.8.4"
sha256 = "1.0.3"
clearscreen = "1.0.9"